language: ruby
rvm:
  - 2.1.5
cache: bundler
bundler_args: --without development --deployment --jobs=3 --retry=3
email:
  recipients:
    - cintrzyk@gmail.com
branches:
  only:
    - master
addons:
  postgresql: '9.3'
env:
  global:
    - RAILS_ENV=test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.travis config/secrets.yml
script: ./travis.sh
